org.gradle.warning.mode=none
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.console=rich
org.gradle.parallel=true

# Plugin versions
kotlinVersion=2.4.20
kotlinterVersion=5.7.0

# Client versions
aaregClientVersion=1.0.5
altinnClientVersion=1.3.0
arbeidsgiverNotifikasjonKlientVersion=4.0.0
brregClientVersion=0.8.0
dokarkivKlientVersion=0.5.3
pdlClientVersion=0.8.1

# Dependency versions
apacheCommonsTextVersion=1.15.0
assertJVersion=3.27.7
bakgrunnsjobbVersion=1.0.7
flywayVersion=13.8.0
gcpStorageVersion=2.74.0
hikariVersion=7.1.0
jacksonModuleKotlinVersion=2.22.3
jacksonVersion=2.22.3
junitJupiterVersion=6.1.3
kafkaClient=4.3.1
kformatVersion=0.14
koinVersion=4.2.2
kotlinxCoroutinesVersion=1.11.0
kotlinxSerializationVersion=1.11.0
ktorVersion=3.6.0
logbackEncoderVersion=9.0
logbackVersion=1.6.4
mockOAuth2ServerVersion=6.0.4
mockkVersion=1.14.11
pdfboxVersion=2.0.37
postgresqlVersion=42.7.13
prometheusVersion=0.16.0
slf4jVersion=2.0.20
tmsVarselKotlinBuilderVersion=2.2.0
tokenSupportVersion=6.0.13
utilsVersion=0.10.2
valiktorVersion=0.12.0
