version: '3.4'

services:
  fritakagp-database:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  fritakagp_kafka:
    image: apache/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"

volumes:
  data:
