apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fritakagp
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    timeout: 2
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10
  ingresses:
    - https://fritakagp.dev.nav.no
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 3500m
      memory: 1000Mi
    requests:
      cpu: 400m
      memory: 200Mi
  webproxy: true
  leaderElection: true
  env:
    - name: KOIN_PROFILE
      value: PREPROD
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: fritakagp-db
            diskAutoresize: true
