apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fritakagp
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /health/is-alive
    initialDelay: 10
    timeout: 2
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /health/is-ready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10
  ingresses:
    - https://fritakagp.dev.nav.no
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 3500m
      memory: 1000Mi
    requests:
      cpu: 400m
      memory: 200Mi
  webproxy: true
  leaderElection: false
  envFrom:
    - configmap: loginservice-idporten # tilgjengeliggjør LOGINSERVICE_IDPORTEN_DISCOVERY_URL og LOGINSERVICE_IDPORTEN_AUDIENCE
  env:
    - name: KOIN_PROFILE
      value: PREPROD
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        tier: db-g1-small
        databases:
          - name: fritakagp-db
            diskAutoresize: true
