apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: fritakagpkrav
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
  annotations:
    dcat.data.nav.no/title: "Fritak AGP Krav"
    dcat.data.nav.no/description: "Krav om refusjon av sykepenger fra arbeidsgiverperioden"
    dcat.data.nav.no/keyword: "sykepenger, gravid, kronisksyk"
    dcat.data.nav.no/theme: "sykepenger"

spec:
  pool: nav-prod
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # -1 means unlimited
  acl:
    - team: helsearbeidsgiver
      application: fritakagp
      access: readwrite   # read, write, readwrite

