apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fritakagp
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50M
    nais.io/read-only-file-system: "false"
    texas.nais.io/enabled: "true"

spec:
  image: {{ image }}
  resources:
    requests:
      cpu: 50m
      memory: 1024Mi
    limits:
      memory: 2048Mi
  replicas:
    max: 1
    min: 1
  liveness:
    path: /health/alive
    initialDelay: 10
    timeout: 2
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /health/ready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10

  tokenx:
    enabled: true
  kafka:
    pool: nav-{{ context }}
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  prometheus:
    enabled: true

  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: fritakagp-db
        {{#if dbTier}}
        tier: {{ dbTier }}
        {{/if}}
        diskAutoresize: true
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
    {{#if bucketName}}
    buckets:
      - name: {{ bucketName }}
        uniformBucketLevelAccess: true
    {{/if}}

  ingresses:
  {{#each ingresses as |ingress|}}
    - {{ ingress }}
  {{/each}}

  {{#if maskinporten}}
  maskinporten:
    enabled: true
    scopes:
      consumes: {{#each maskinporten.consumes as |consume| }}
        - name: "{{ consume }}"
    {{/each }}
  {{/if }}

  accessPolicy:
    outbound:
      rules:
        - application: clamav
          namespace: nais-system
        {{#each accessOutbound.apps as |app|}}
        - application: {{ app.name }}
          namespace: {{ app.namespace }}
        {{/each}}

      {{#if accessOutbound.external}}
      external:
        {{#each accessOutbound.external as |host|}}
        - host: {{ host }}
        {{/each}}
      {{/if}}
    inbound:
      rules:
        {{# each accessInbound.apps as |app| }}
        - application: {{ app.name }}
          namespace: {{ app.namespace }}
        {{/each}}
  envFrom:
    {{#each envFrom as |secret|}}
    - secret: {{ secret }}
    {{/each}}

  env:
    - name: KAFKA_BESKJED_TOPIC_NAME
      value: min-side.aapen-brukervarsel-v1
    - name: CLAM_AV_URL
      value: http://clamav.nais-system/scan
    {{#each env as |var|}}
    - name: {{ var.name }}
      value: "{{ var.value }}"
    {{/each}}
