apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fritakagp
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /health/is-alive
    initialDelay: 10
    timeout: 2
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /health/is-ready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10
  ingresses:
    - https://arbeidsgiver.nav.no/fritak-agp-api
    - https://fritakagp-api.intern.nav.no
  prometheus:
    enabled: true
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 3500m
      memory: 1000Mi
    requests:
      cpu: 400m
      memory: 200Mi
  leaderElection: false
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true

  accessPolicy:
    outbound:
      external:
        - host: helsearbeidsgiver-proxy.prod-fss-pub.nais.io
        - host: www.altinn.no
        - host: kafka-schema-registry.nais.adeo.no
        - host: data.brreg.no
        - host: dokarkiv.prod-fss-pub.nais.io
        - host: oppgave.prod-fss-pub.nais.io

      rules:
        - application: helsearbeidsgiver-proxy
          namespace: helsearbeidsgiver
          cluster: prod-fss
        - application: clamav
          namespace: clamav

  envFrom:
    # servicebrukerens passord som er  hentet fra vault og lagt inn slik: https://doc.nais.io/security/secrets/kubernetes-secrets/
    - secret: service-user-password-prod
    - secret: altinn-user-password-prod
    - secret: altinn-api-gw-keys-prod
    - configmap: loginservice-idporten # tilgjengeliggjør LOGINSERVICE_IDPORTEN_DISCOVERY_URL og LOGINSERVICE_IDPORTEN_AUDIENCE
  env:
    - name: KOIN_PROFILE
      value: PROD
    - name: PDL_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/pdl
    - name: ALTINN_ENDPOINT
      value: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
    - name: CLAM_AV_URL
      value: http://clamav.clamav.svc.cluster.local/scan
    - name: GCP_PRJ_ID
      value: helsearbeidsgiver-prod-8a1c
    - name: GCP_BUCKET_NAME
      value: helse-arbeidsgiver-fritakagb-bucket-prod
    - name: ALTINN_SERVICE_OWNER_GW_URL
      value: https://api-gw.oera.no/ekstern/altinn/api/serviceowner
    - name: ENHETSREGISTERET
      value: https://data.brreg.no/enhetsregisteret/api/underenheter
    - name: KAFKA_BESKJED_TOPIC_NAME
      value: min-side.aapen-brukernotifikasjon-beskjed-v1
    - name: PROXY_SCOPE
      value: api://prod-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default
    - name: KTOR_APPLICATION_BASEPATH
      value: /fritak-agp-api
    - name: RUN_BACKGROUND_WORKERS
      value: "true"
    - name: AAREG_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/aareg-arbeidsforhold
    - name: OPPGAVE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: DOKARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: DOKARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: DATAPAKKE_ID
      value: "a4570c9e9521df726e1050ebcd917b9a"
    - name: DATAPAKKE_API_URL
      value: "https://datakatalog-api.intern.nav.no/v1/datapackage"
    - name: NORG2_URL
      value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/norg

  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: fritakagp-db
            diskAutoresize: true
    buckets:
      - name: helse-arbeidsgiver-fritakagb-bucket-prod
        uniformBucketLevelAccess: true
        #retentionPeriodDays: 30
         # lifecycleCondition:
         # age: 7
         # createdBefore: 2020-01-01
         # numNewerVersions: 2
        #  withState: ANY

  kafka:
    pool: nav-prod    # enum of nav-dev, nav-prod
