context: prod
bucketName: helse-arbeidsgiver-fritakagb-bucket-prod
dbTier: db-custom-1-3840
ingresses:
  - https://fritakagp-api.intern.nav.no
accessOutbound:
  external:
    - kafka-schema-registry.nais.adeo.no
    - dokarkiv.prod-fss-pub.nais.io
    - helsearbeidsgiver-proxy.prod-fss-pub.nais.io
    - oppgave.prod-fss-pub.nais.io
    - ag-notifikasjon-produsent-api.intern.nav.no
    - api-gw.oera.no
    - www.altinn.no
    - data.brreg.no
    - g.nav.no
    - idporten.no
envFrom:
  # servicebrukerens passord som er  hentet fra vault og lagt inn slik: https://doc.nais.io/security/secrets/kubernetes-secrets/
  - service-user-password-prod
  - altinn-user-password-prod
  - altinn-api-gw-keys-prod
env:
  - name: KOIN_PROFILE
    value: PROD
  - name: KTOR_APPLICATION_BASEPATH
    value: /fritak-agp-api
  - name: GCP_PRJ_ID
    value: helsearbeidsgiver-prod-8a1c
  - name: GCP_BUCKET_NAME
    value: helse-arbeidsgiver-fritakagb-bucket-prod
  - name: ARBEIDSGIVER_NOTIFIKASJON_SCOPE
    value: api://prod-gcp.fager.notifikasjon-produsent-api/.default
  - name: DOKARKIV_SCOPE
    value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
  - name: OPPGAVE_SCOPE
    value: api://prod-fss.oppgavehandtering.oppgave/.default
  - name: PROXY_SCOPE
    value: api://prod-fss.helsearbeidsgiver.helsearbeidsgiver-proxy/.default
  - name: FRONTEND_URL
    value: https://arbeidsgiver.nav.no/fritak-agp
    # TODO ikke i dev
  - name: AAREG_URL
    value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/aareg-arbeidsforhold
  - name: ARBEIDSGIVER_NOTIFIKASJON_API_URL
    value: https://ag-notifikasjon-produsent-api.intern.nav.no/api/graphql
  - name: DOKARKIV_URL
    value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1
  - name: GRUNNBELOEP_URL
    value: https://g.nav.no/api/v1/grunnbeløp
  - name: NORG2_URL
    value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/norg
  - name: OPPGAVEBEHANDLING_URL
    value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
  - name: PDL_URL
    value: https://helsearbeidsgiver-proxy.prod-fss-pub.nais.io/pdl
  - name: ALTINN_SERVICE_OWNER_GW_URL
    value: https://api-gw.oera.no/ekstern/altinn/api/serviceowner
  - name: ALTINN_ENDPOINT
    value: https://www.altinn.no/ServiceEngineExternal/CorrespondenceAgencyExternalBasic.svc
  - name: ENHETSREGISTERET
    value: https://data.brreg.no/enhetsregisteret/api/underenheter
