apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: fritakagpsoeknad
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
  annotations:
    dcat.data.nav.no/title: "Fritak AGP Søknader"
    dcat.data.nav.no/description: "Søknader om fritak fra arbeidsgiverperioden for sykepenger"
    dcat.data.nav.no/keyword: "sykepenger, gravid, kronisksyk"
    dcat.data.nav.no/theme: "sykepenger"

spec:
  pool: nav-dev
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # -1 means unlimited
  acl:
    - team: helsearbeidsgiver
      application: fritakagp
      access: readwrite   # read, write, readwrite

