name: Preprod

on:
  push:
    branches:
      - main
      - 'preprod/**'
      - 'dev/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: compose up
        run: cd docker/local && docker compose up -d && sleep 15

      - name: Build and test
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: --console=plain build test jar
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push
        uses: nais/docker-build-push@v0
        with:
          team: helsearbeidsgiver
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

  deploy-to-dev:
    name: Deploy to dev-gcp
    needs: buildAndTest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/nais.yml
          VAR: image=${{ env.IMAGE }}:${{ github.sha }}
          VARS: deploy/dev.yml
