name: Preprod

on:
  push:
    branches:
      - main
      - 'preprod/**'
      - 'dev/**'

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: compose up
        run: cd docker/local && docker compose up -d && sleep 15

      - uses: gradle/actions/setup-gradle@v4

      - name: Build and test
        run: ./gradlew build test jar --console=plain
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker-build-push
        uses: nais/docker-build-push@v0
        with:
          team: helsearbeidsgiver
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/nais.yml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
          VARS: deploy/dev.yml
