name: Preprod

on:
  push:
    branches:
      - main
      - 'preprod/**'
      - 'dev/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: compose up
        run: cd docker/local && docker compose up -d && sleep 15

      - name: Build and test
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: --console=plain build test jar
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: nais/docker-build-push@v0
        with:
          team: helsearbeidsgiver
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml
          VAR: image=${{ steps.docker-build-push.outputs.image }}